# Generated by Django 4.1.5 on 2023-01-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore_app', '0002_order_alter_book_bookpage_alter_book_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='total_review',
        ),
        migrations.AlterField(
            model_name='book',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
