# Generated by Django 4.1.5 on 2023-01-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore_app', '0004_wishlist_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
